kind: pipeline
type: exec
name: default

platform:
  os: windows
  arch: amd64

steps:
- name: greeting
  commands:
  - echo hello world
- name: build
  commands: 
  - G:\VS2019\MSBuild\Current\Bin\MSBuild.exe leptjson.sln /t:Rebuild /p:Configuration=Release;Platform=x86